### ISSUE TITLE
Xbox one control does not recognize it  

### ISSUE THREAD

**Issue by Swivloc** [Maschell/controller_patcher#27]
My old Xbox one control of the first version connects to the Wii u or perfectly the light stays static But when the window appears, any button does not recognize it and I have the xinput.ini file but it does not recognize it

**Comment by Maschell** [comment]
Are you using the network client? You can't connect to the controller directly to the console

**Comment by Swivloc** [comment]
I did not know that I thought I could connect directly like PS3 or PS4, thanks for the information

**Comment by Swivloc** [comment]
Another doubt the controls of the Xbox one s, x if they can be connected directly or the same has to be by network client

**Comment by Maschell** [comment]
All of them are no HID devices but XInput devices. The network client will convert them to HID for HID to VPAD. So **ANY** XInput device needs to be handled by the [network client](https://gbatemp.net/threads/hid-to-vpad-network-client.466150/).

**Comment by Swivloc** [comment]
ok it's good to know thank you
