### ISSUE TITLE
Could not convert 'false' from 'bool' to 'std_::__cxx11::string {aka std::__cxx11::basic_string<char>}'

### ISSUE THREAD

**Issue by BtheDestroyer** [Maschell/controller_patcher#6]
Trying to set up my computer for Wii U development and using loadiine to test that everything works. Ran into this error when it got to controller_patcher:

```
config_reader.cpp
/home/bthedestroyer/Documents/WiiUHacking/loadiine_gx2/src/controller_patcher/config_reader.cpp: In member function 'std::__cxx11::string ConfigReader::loadFileToString(std::__cxx11::string)':
/home/bthedestroyer/Documents/WiiUHacking/loadiine_gx2/src/controller_patcher/config_reader.cpp:65:11: error: could not convert 'false' from 'bool' to 'std::__cxx11::string {aka std::__cxx11::basic_string<char>}'
    return false;
           ^~~~~
/home/bthedestroyer/Documents/WiiUHacking/loadiine_gx2/src/controller_patcher/config_reader.cpp:79:20: error: could not convert 'false' from 'bool' to 'std::__cxx11::string {aka std::__cxx11::basic_string<char>}'
             return false;
                    ^~~~~
/home/bthedestroyer/Documents/WiiUHacking/loadiine_gx2/Makefile:191: recipe for target 'config_reader.o' failed
```

Any tips?

**Comment by Maschell** [comment]
Which devkit version are you using?

**Comment by BtheDestroyer** [comment]
DevkitPPC r28 for 64 bit Linux. I replaced stdint.h with an older version as the latest version kind of breaks everything.

libfat-ogc-1.0.13

portlibs and libogc provided by dimok in [Loadiine_GX2 Open Beta Release v0.2](https://github.com/dimok789/loadiine_gx2/releases/tag/v0.2)

**Comment by Maschell** [comment]
Change the false to "", this should fix the problem (r27 was able to compile it though)

**Comment by BtheDestroyer** [comment]
Reverted to r27 (r28 had a ton of issues anyway) and the compile finished. Now I'm getting a giant linker error, but that's more of a Loadiine GX2 issue so I'll close this issue. Thanks for the help.
