### ISSUE TITLE
Remapping Issue.

### ISSUE THREAD

**Issue by seki777** [Maschell/controller_patcher#7]
I'm using a DS4, only trying to remap Cross to Circle and vise versa. 

my VID and PID and in brackets on the first line. 
Ignore defaults in brackets on the second. 

What i have:

[vid=0x054c,pid=0x05c4]
[IgnoreDefault] //Ignoring the built in default values

//Settings buttons 
VPAD_BUTTON_A                   =   DS4_BUTTON_CROSS
VPAD_BUTTON_B                   =   DS4_BUTTON_CIRCLE
VPAD_BUTTON_X                   =   DS4_BUTTON_TRIANGLE
VPAD_BUTTON_Y                   =   DS4_BUTTON_SQUARE
VPAD_BUTTON_MINUS               =   DS4_BUTTON_SELECT
VPAD_BUTTON_PLUS                =   DS4_BUTTON_START

VPAD_BUTTON_STICK_L             =   DS4_BUTTON_L3
VPAD_BUTTON_STICK_R             =   DS4_BUTTON_R3

//Setting dpad
DPAD_MODE                       =   DS4_DPAD_MODE
VPAD_BUTTON_LEFT                =   DS4_BUTTON_LEFT
VPAD_BUTTON_RIGHT               =   DS4_BUTTON_RIGHT
VPAD_BUTTON_UP                  =   DS4_BUTTON_UP
VPAD_BUTTON_DOWN                =   DS4_BUTTON_DOWN

//Setting the sticks
VPAD_BUTTON_L_STICK_X           =   DS4_STICK_L_X
VPAD_BUTTON_L_STICK_Y           =   DS4_STICK_L_Y
VPAD_BUTTON_R_STICK_X           =   DS4_STICK_R_X
VPAD_BUTTON_R_STICK_Y           =   DS4_STICK_R_Y

//Setting the trigger
VPAD_BUTTON_L                   =   DS4_BUTTON_L1
VPAD_BUTTON_ZL                  =   DS4_BUTTON_L2
VPAD_BUTTON_R                   =   DS4_BUTTON_R1
VPAD_BUTTON_ZR                  =   DS4_BUTTON_R2
//This device is no adapter that can't have more than 1 pads.
PAD_COUNT                       =   0x01

From my understanding of the wiki, this overwrites the default even though it is the default controls. So by swapping the buttons all should be well. Just plop in the wiiu/controller folder and it should work. 

I read the wiki and it tells me it doesn't even matter what the .ini is named, just as long as your VID AND PID are correct it should pick up the control and apply the config. To me it sems like no matter I do, default every single time.

**Comment by seki777** [comment]
Hey! I see the hotfix!

Allows controllers with default to use configs! 

Thank you, I am not crazy

**Comment by Maschell** [comment]
I'm glad I could help you
