### ISSUE TITLE
Remapping issue KB/M. Default only - even with config.

### ISSUE THREAD

**Issue by seki777** [Maschell/controller_patcher#8]
I believe it's happening again but on Keyboard. According to examples provided this should be proper. I've tried a capital K and a lower case one as well. The wiki said it's case sensitive but goes on to have both capitalizations. You should probably alter the text to avoid confusion.  When I set ignore default nothing worked. I've also tried spaces between each = sign as well because that's how the ps4 controller worked and that guide had it differently. All out of ideas here so I think it's the default problem again.
[keyboard]
VPAD_BUTTON_A=KEYBOARD_W
VPAD_BUTTON_B=KEYBOARD_S
VPAD_BUTTON_PLUS=KEYBOARD_RETURN
VPAD_BUTTON_MINUS=KEYBOARD_RIGHT_SHIFT
VPAD_BUTTON_LEFT=KEYBOARD_LEFT
VPAD_BUTTON_RIGHT=KEYBOARD_RIGHT
VPAD_BUTTON_UP=KEYBOARD_UP
VPAD_BUTTON_DOWN=KEYBOARD_DOWN
VPAD_BUTTON_ZR=KEYBOARD_SPACEBAR
VPAD_BUTTON_ZL=KEYBOARD_SHIFT
VPAD_L_STICK_UP=KEYBOARD_2
VPAD_L_STICK_DOWN=KEYBOARD_X
VPAD_L_STICK_RIGHT=KEYBOARD_A
VPAD_L_STICK_LEFT=KEYBOARD_D

P.S. This is a good mario kart 8 config. feel free to use

**Comment by Maschell** [comment]
Oh.
Can you try this .elf? 
[hidtovpad.zip](https://github.com/Maschell/controller_patcher/files/887747/hidtovpad.zip)

**Comment by seki777** [comment]
Works perfect now~~~ 

Thank you so much for the swift fixes. You got skills Maschell, skills. 

I'll keep looking out for various bugs, will send them in but don't stress about it. Take your time you swift beast.

**Comment by Maschell** [comment]
I'm glad this is now working. Thank you for reporting
